Lethe Open-Source Library: RPTFEMReconstruction< dim > Class Template Reference
RPTFEMReconstruction< dim > Class Template Reference
#include <rpt_fem_reconstruction.h>
Public Member Functions
RPTFEMReconstruction (Parameters::RPTParameters &rpt_parameters, Parameters::RPTFEMReconstructionParameters &rpt_fem_reconstruction_parameters, Parameters::DetectorParameters &rpt_detector_parameters)
void rpt_fem_reconstruct ()
Private Member Functions
void setup_triangulation ()
double calculate_cost (const TriaActiveIterator< DoFCellAccessor< dim, dim, false > > &cell, Vector< double > &reference_location, const double &last_constraint, std::vector< double > &experimental_count)
double calculate_reference_location_error (Vector< double > &reference_location, const double &last_constraint)
void search_position_in_reference_space (std::vector< std::vector< double > > &count_from_all_detectors, std::vector< double > &experimental_count, const typename DoFHandler< dim >::active_cell_iterator &cell, const double &tol_reference_location, double &max_cost, Vector< double > &reference_location, bool &position_found, Point< dim > &real_location)
bool find_position_global_search (std::vector< double > &experimental_counts, const double tol_reference_location)
bool find_position_local_search (std::vector< double > &experimental_counts, const double tol_reference_location)
void trajectory ()
void checkpoint ()
void load_from_checkpoint ()
void export_found_positions ()
Private Attributes
Triangulation< dim > triangulation
FE_SimplexP< dim > fe
DoFHandler< dim > dof_handler
RPTCalculatingParameters rpt_parameters
MappingFE< dim > mapping
Parameters::RPTParameters parameters
Parameters::RPTFEMReconstructionParameters fem_reconstruction_parameters
Parameters::DetectorParameters detector_parameters
std::vector< Detector< dim > > detectors
unsigned int n_detector
std::vector< Vector< double > > nodal_counts
std::vector< Point< dim > > found_positions
DoFHandler< dim >::active_cell_iterator previous_position_cell
TimerOutput computing_timer
Detailed Description
template<int dim>
class RPTFEMReconstruction< dim >
Definition at line 180 of file rpt_fem_reconstruction.h.
Constructor & Destructor Documentation
RPTFEMReconstruction()
template<int dim> RPTFEMReconstruction< dim >::RPTFEMReconstruction (Parameters::RPTParameters & rpt_parameters, Parameters::RPTFEMReconstructionParameters & rpt_fem_reconstruction_parameters, Parameters::DetectorParameters & rpt_detector_parameters) inline
Constructor for the RPTFEMReconstruction.
Parameters
rpt_parameters General parameters for photon count calculation with the Monte Carlo method and setting up the grid
rpt_fem_reconstruction_parameters Parameters for the particle position reconstruction
rpt_detector_parameters Parameters specifying information about the detectors for photon count calculation with the Monte Carlo method
Definition at line 190 of file rpt_fem_reconstruction.h.
Member Function Documentation
calculate_cost()
template<int dim> double RPTFEMReconstruction< dim >::calculate_cost (const TriaActiveIterator< DoFCellAccessor< dim, dim, false > > & cell, Vector< double > & reference_location, const double & last_constraint, std::vector< double > & experimental_count) private
Calculates the cost with the selected cost function of the found position and returns it.
Parameters
cell Iterator on active cells of the grid.
reference_location Location of the particle in reference coordinates
last_constraint Constraint on the particle's location
experimental_count Experimental counts from all detectors for a given particle position
Returns
cost It is calculated with the cost function mentioned in the parameter file.
Definition at line 637 of file rpt_fem_reconstruction.cc.
References Parameters::RPTFEMReconstructionParameters::absolute, and convert_string_to_vector().
calculate_reference_location_error()
template<int dim> double RPTFEMReconstruction< dim >::calculate_reference_location_error (Vector< double > & reference_location, const double & last_constraint) private
Evaluates the error vector of the found location in reference coordinates and returns the error vector's L2 norm.
Parameters
reference_location Location of the point in reference coordinates
last_constraint 4th constraint on the location of the particle in reference coordinates
Returns
norm_error_coordinates
Definition at line 594 of file rpt_fem_reconstruction.cc.
References convert_string_to_vector().
checkpoint()
template<int dim> void RPTFEMReconstruction< dim >::checkpoint () private
Saves the built dictionary so it may be used later for the 3D particle position reconstruction.
export_found_positions()
template<int dim> void RPTFEMReconstruction< dim >::export_found_positions () private
Exports found particle positions in a the specified file format. If not specified, it will be exported in a ".csv" file format.
Definition at line 1006 of file rpt_fem_reconstruction.cc.
References convert_string_to_vector(), and Parameters::verbose.
find_position_global_search()
template<int dim> bool RPTFEMReconstruction< dim >::find_position_global_search (std::vector< double > & experimental_counts, const double tol_reference_location) private
Finds and saves the position of the particle in system coordinates.
Parameters
experimental_counts experimental_count contains the experimental counts of every detector for a given position.
tol_reference_location tolerance on the validity of the found location in the reference space
Returns
'true' if the particle's position was found and 'false' if the particle's position couldn't be found
Definition at line 761 of file rpt_fem_reconstruction.cc.
References convert_string_to_vector().
find_position_local_search()
template<int dim> bool RPTFEMReconstruction< dim >::find_position_local_search (std::vector< double > & experimental_counts, const double tol_reference_location) private
Finds and saves the position of the particle in system coordinates by doing a local search around the previously found position's cell's neighbors.
Parameters
experimental_counts experimental_count contains the experimental counts of every detector for a given position.
tol_reference_location tolerance on the validity of the found location in the reference space
Returns
'true' if the particle's position was found and 'false' if the particle's position couldn't be found
Definition at line 799 of file rpt_fem_reconstruction.cc.
References convert_string_to_vector().
load_from_checkpoint()
template<int dim> void RPTFEMReconstruction< dim >::load_from_checkpoint () private
Loads the previously built dictionary for the 3D particle position reconstruction.
Definition at line 975 of file rpt_fem_reconstruction.cc.
References convert_string_to_vector().
rpt_fem_reconstruct()
template<int dim> void RPTFEMReconstruction< dim >::rpt_fem_reconstruct ()
Reconstruction of the particle positions with the counts from the detectors.
Definition at line 1078 of file rpt_fem_reconstruction.cc.
search_position_in_reference_space()
template<int dim> void RPTFEMReconstruction< dim >::search_position_in_reference_space (std::vector< std::vector< double > > & count_from_all_detectors, std::vector< double > & experimental_count, const typename DoFHandler< dim >::active_cell_iterator & cell, const double & tol_reference_location, double & max_cost, Vector< double > & reference_location, bool & position_found, Point< dim > & real_location) private
Searches in the reference space the position of the particle. If the found position respects the set tolerance, and the calculated cost is minimal it calculates and stores the position of the particle in system coordinates.
Parameters
count_from_all_detectors Contains the photon counts of all detectors for all vertices of a cell.
experimental_count Experimental counts from all detectors for a given particle position
cell Cell where the particle's position is being searched
tol_reference_location Tolerance on the validity of the found location in the reference space
max_cost Cost that has to be minimized in order to find a particle's real position
reference_location Position of the particle in reference coordinates
position_found Bool,'true' if the particle's position was found, and 'false' if the particle's position couldn't be found
real_location Position of the particle in system coordinates
Definition at line 699 of file rpt_fem_reconstruction.cc.
References convert_string_to_vector().
setup_triangulation()
template<int dim> void RPTFEMReconstruction< dim >::setup_triangulation () private
Set up the triangulation that covers the domain of the reactor.
Definition at line 108 of file rpt_fem_reconstruction.cc.
References convert_string_to_vector(), and Parameters::RPTFEMReconstructionParameters::gmsh.
trajectory()
template<int dim> void RPTFEMReconstruction< dim >::trajectory () private
Reads the file with the experimental counts and finds the particles' positions by calling the "find_cell" function.
Definition at line 907 of file rpt_fem_reconstruction.cc.
References convert_string_to_vector(), Parameters::RPTFEMReconstructionParameters::dealii, and Parameters::RPTFEMReconstructionParameters::local.
Member Data Documentation
computing_timer
template<int dim> TimerOutput RPTFEMReconstruction< dim >::computing_timer private
Definition at line 366 of file rpt_fem_reconstruction.h.
detector_parameters
template<int dim> Parameters::DetectorParameters RPTFEMReconstruction< dim >::detector_parameters private
Definition at line 358 of file rpt_fem_reconstruction.h.
detectors
template<int dim> std::vector<Detector<dim> > RPTFEMReconstruction< dim >::detectors private
Definition at line 360 of file rpt_fem_reconstruction.h.
dof_handler
template<int dim> DoFHandler<dim> RPTFEMReconstruction< dim >::dof_handler private
Definition at line 353 of file rpt_fem_reconstruction.h.
fe
template<int dim> FE_SimplexP<dim> RPTFEMReconstruction< dim >::fe private
Definition at line 352 of file rpt_fem_reconstruction.h.
fem_reconstruction_parameters
template<int dim> Parameters::RPTFEMReconstructionParameters RPTFEMReconstruction< dim >::fem_reconstruction_parameters private
Definition at line 357 of file rpt_fem_reconstruction.h.
found_positions
template<int dim> std::vector<Point<dim> > RPTFEMReconstruction< dim >::found_positions private
Definition at line 363 of file rpt_fem_reconstruction.h.
mapping
template<int dim> MappingFE<dim> RPTFEMReconstruction< dim >::mapping private
Definition at line 355 of file rpt_fem_reconstruction.h.
n_detector
template<int dim> unsigned int RPTFEMReconstruction< dim >::n_detector private
Definition at line 361 of file rpt_fem_reconstruction.h.
nodal_counts
template<int dim> std::vector<Vector<double> > RPTFEMReconstruction< dim >::nodal_counts private
Definition at line 362 of file rpt_fem_reconstruction.h.
parameters
template<int dim> Parameters::RPTParameters RPTFEMReconstruction< dim >::parameters private
Definition at line 356 of file rpt_fem_reconstruction.h.
previous_position_cell
template<int dim> DoFHandler<dim>::active_cell_iterator RPTFEMReconstruction< dim >::previous_position_cell private
Definition at line 364 of file rpt_fem_reconstruction.h.
rpt_parameters
template<int dim> RPTCalculatingParameters RPTFEMReconstruction< dim >::rpt_parameters private
Definition at line 354 of file rpt_fem_reconstruction.h.
triangulation
template<int dim> Triangulation<dim> RPTFEMReconstruction< dim >::triangulation private
Definition at line 351 of file rpt_fem_reconstruction.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe-rpt/lethe-rpt/include/rpt/rpt_fem_reconstruction.h
/home/runner/work/lethe-rpt/lethe-rpt/source/rpt/rpt_fem_reconstruction.cc