Lethe Open-Source Library: /home/runner/work/lethe-rpt/lethe-rpt/include/core/solutions_output.h File Reference
solutions_output.h File Reference
#include <core/pvd_handler.h>
#include <deal.II/numerics/data_out.h>
#include <deal.II/numerics/data_out_faces.h>
Functions
template<int dim, int spacedim = dim>
void write_vtu_and_pvd (PVDHandler &pvd_handler, const DataOutInterface< dim, spacedim > &data_out, const std::string &folder, const std::string &file_prefix, const double time, const unsigned int iter, const unsigned int group_files, const MPI_Comm &mpi_communicator, const unsigned int digits=5)
template<int dim>
void write_boundaries_vtu (const DataOutFaces< dim > &data_out, const std::string &folder, const double time, const unsigned int iter, const MPI_Comm &mpi_communicator, const std::string &file_prefix=std::string("boundaries"), const unsigned int digits=5)
template<int dim>
void write_boundaries_vtu_and_pvd (PVDHandler &pvd_handler_boundary, const DataOutFaces< dim > &data_out_faces, const std::string &folder, const double time, const unsigned int iter, const unsigned int group_files, const MPI_Comm &mpi_communicator, const std::string &file_prefix=std::string("boundaries"), const unsigned int digits=5)
Function Documentation
write_boundaries_vtu()
template<int dim> void write_boundaries_vtu (const DataOutFaces< dim > & data_out, const std::string & folder, const double time, const unsigned int iter, const MPI_Comm & mpi_communicator, const std::string & file_prefix = std::string("boundaries"), const unsigned int digits = 5)
Output the Data Out Faces to a single vtu file This function outputs the DataOutFaces to a vtu file.
Parameters
[in] data_out the DataOutFaces class to which the data has been attached
[in] folder a string that contains the path where the results are to be saved
[in] time the time associated with the file
[in] iter the iteration number associated with the file
[in] mpi_communicator The mpi communicator
[in] file_prefix a string that stores the name of the file without the iteration number and the extension
[in] digits An optional parameter that specifies the amount of digit used to store iteration number in the file name
Definition at line 67 of file solutions_output.cc.
References convert_string_to_vector().
write_boundaries_vtu_and_pvd()
template<int dim> void write_boundaries_vtu_and_pvd (PVDHandler & pvd_handler_boundary, const DataOutFaces< dim > & data_out_faces, const std::string & folder, const double time, const unsigned int iter, const unsigned int group_files, const MPI_Comm & mpi_communicator, const std::string & file_prefix = std::string("boundaries"), const unsigned int digits = 5)
Output the Data Out Faces as vtu files, with a pvtu file and a pvd to store the timing This function is used only when the mortar feature is enabled, since the rotating domain changes its boundary position over time.
Parameters
[in] pvd_handler a PVDHandler to store the information about the file name and time associated with it
[in] data_out_faces the DataOutFaces class to which the data has been attached
[in] folder a string that contains the path where the results are to be saved
[in] time the time associated with the file
[in] iter the iteration number associated with the file
[in] group_files the number of vtu files that will be generated.
[in] mpi_communicator The mpi communicator
[in] file_prefix a string that stores the name of the file without the iteration number and the extension
[in] digits An optional parameter that specifies the amount of digit used to store iteration number in the file name
[in] file_prefix a string that stores the name of the file without the iteration number and the extension.
[in] digits An optional parameter that specifies the amount of digit used to store iteration number in the file name
Definition at line 88 of file solutions_output.cc.
References convert_string_to_vector().
write_vtu_and_pvd()
template<int dim, int spacedim = dim> void write_vtu_and_pvd (PVDHandler & pvd_handler, const DataOutInterface< dim, spacedim > & data_out, const std::string & folder, const std::string & file_prefix, const double time, const unsigned int iter, const unsigned int group_files, const MPI_Comm & mpi_communicator, const unsigned int digits = 5)
Output the data out to "group_files" vtu files, with a pvtu file and a pvd to store the timing This function outputs the data out to "group_files" vtu file that are orchestrated by a .pvtu file. An additional pvd file takes care of storing the time associated with each .pvtu file.
Parameters
[in] pvd_handler a PVDHandler to store the information about the file name and time associated with it
[in] data_out the DataOut class to which the data has been attached
[in] folder a string that contains the path where the results are to be saved
[in] file_prefix a string that stores the name of the file without the iteration number and the extension
[in] time the time associated with the file
[in] iter the iteration number associated with the file
[in] group_files the number of vtu files that will be generated.
[in] mpi_communicator The mpi communicator
[in] digits An optional parameter that specifies the amount of digit used to store iteration number in the file name
Definition at line 15 of file solutions_output.cc.
References convert_string_to_vector().