Lethe Open-Source Library: /home/runner/work/lethe-rpt/lethe-rpt/source/core/utilities.cc File Reference
utilities.cc File Reference
#include <core/revision.h>
#include <core/utilities.h>
#include <deal.II/base/revision.h>
Functions
template<typename T >
TableHandler make_table_scalars_vectors (const std::vector< T > &independent_values, const std::string &independent_column_name, const std::vector< std::vector< double > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template<int dim, typename T >
TableHandler make_table_scalars_tensors (const std::vector< T > &independent_vector, const std::string &independent_column_name, const std::vector< Tensor< 1, dim > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template<int dim, typename T >
TableHandler make_table_scalars_tensors (const std::vector< T > &independent_vector, const std::string &independent_column_name, const std::vector< std::vector< Tensor< 1, dim > > > &dependent_vectors, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template<int dim>
TableHandler make_table_tensors_tensors (const std::vector< Tensor< 1, dim > > &independent_vector, const std::vector< std::string > &independent_column_names, const std::vector< Tensor< 1, dim > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template<int dim>
TableHandler make_table_tensors_scalars (const std::vector< Tensor< 1, dim > > &independent_vector, const std::vector< std::string > &independent_column_names, const std::vector< double > &dependent_vector, const std::string &dependent_column_name, const unsigned int display_precision, const bool display_scientific_notation)
void fill_table_from_file (TableHandler &table, const std::string &file_name, const std::string &delimiter)
void fill_vectors_from_file (std::map< std::string, std::vector< double > > &map, const std::string &file, const std::string &delimiter)
void fill_string_vectors_from_file (std::map< std::string, std::vector< std::string > > &map, const std::string &file, const std::string &delimiter)
void create_output_folder (const std::string &dirname)
void delete_output_folder (const std::string &dirname)
template TableHandler make_table_scalars_vectors (const std::vector< double > &independent_values, const std::string &independent_column_name, const std::vector< std::vector< double > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_scalars_vectors (const std::vector< unsigned int > &independent_values, const std::string &independent_column_name, const std::vector< std::vector< double > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_scalars_vectors (const std::vector< int > &independent_values, const std::string &independent_column_name, const std::vector< std::vector< double > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_scalars_tensors (const std::vector< double > &independent_values, const std::string &independent_column_name, const std::vector< Tensor< 1, 2 > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_scalars_tensors (const std::vector< double > &independent_values, const std::string &independent_column_name, const std::vector< Tensor< 1, 3 > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_scalars_tensors (const std::vector< double > &independent_values, const std::string &independent_column_name, const std::vector< std::vector< Tensor< 1, 2 > > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_scalars_tensors (const std::vector< double > &independent_values, const std::string &independent_column_name, const std::vector< std::vector< Tensor< 1, 3 > > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_scalars_tensors (const std::vector< unsigned int > &independent_values, const std::string &independent_column_name, const std::vector< Tensor< 1, 2 > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_scalars_tensors (const std::vector< unsigned int > &independent_values, const std::string &independent_column_name, const std::vector< Tensor< 1, 3 > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_scalars_tensors (const std::vector< unsigned int > &independent_values, const std::string &independent_column_name, const std::vector< std::vector< Tensor< 1, 2 > > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_scalars_tensors (const std::vector< unsigned int > &independent_values, const std::string &independent_column_name, const std::vector< std::vector< Tensor< 1, 3 > > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_scalars_tensors (const std::vector< int > &independent_values, const std::string &independent_column_name, const std::vector< Tensor< 1, 2 > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_scalars_tensors (const std::vector< int > &independent_values, const std::string &independent_column_name, const std::vector< Tensor< 1, 3 > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_scalars_tensors (const std::vector< int > &independent_values, const std::string &independent_column_name, const std::vector< std::vector< Tensor< 1, 2 > > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_scalars_tensors (const std::vector< int > &independent_values, const std::string &independent_column_name, const std::vector< std::vector< Tensor< 1, 3 > > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_tensors_tensors (const std::vector< Tensor< 1, 2 > > &independent_values, const std::vector< std::string > &independent_column_names, const std::vector< Tensor< 1, 2 > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_tensors_tensors (const std::vector< Tensor< 1, 3 > > &independent_values, const std::vector< std::string > &independent_column_names, const std::vector< Tensor< 1, 3 > > &dependent_vector, const std::vector< std::string > &dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_tensors_scalars (const std::vector< Tensor< 1, 2 > > &independent_vector, const std::vector< std::string > &independent_column_names, const std::vector< double > &dependent_values, const std::string &dependent_column_name, const unsigned int display_precision, const bool display_scientific_notation)
template TableHandler make_table_tensors_scalars (const std::vector< Tensor< 1, 3 > > &independent_vector, const std::vector< std::string > &independent_column_names, const std::vector< double > &dependent_values, const std::string &dependent_column_name, const unsigned int display_precision, const bool display_scientific_notation)
std::string get_last_value_of_parameter (const std::string &file_name, const std::string &parameter_name)
int get_max_value_of_parameter (const std::string &file_name, const std::string &parameter_name)
unsigned int get_dimension (const std::string &file_name)
int get_max_subsection_size (const std::string &file_name)
std::string concatenate_strings (const int argc, char **argv)
void print_version_info (const ConditionalOStream &pcout)
std::tuple< std::map< std::string, bool >, std::vector< std::string > > parse_args (int argc, char **argv)
void print_parameters_to_output_file (const ConditionalOStream &pcout, const ParameterHandler &prm, const std::string &file_name)
void delete_vtu_and_pvd_files (const std::string &output_path)
Function Documentation
concatenate_strings()
std::string concatenate_strings (const int argc, char ** argv)
Concatenate words which are passed from the command line to a main function into a single string in which the words are seperated by space.
Parameters
[in] argc number of arguments in C style.
[in] argv arguments themselves in C style.
Definition at line 720 of file utilities.cc.
References convert_string_to_vector().
create_output_folder()
void create_output_folder (const std::string & dirname)
Creates the simulation output folder.
Parameters
[in] dirname Output directory name
Definition at line 358 of file utilities.cc.
References convert_string_to_vector().
delete_output_folder()
void delete_output_folder (const std::string & dirname)
Delete the output folder and its content.
Parameters
[in] dirname Output directory name.
Definition at line 369 of file utilities.cc.
References convert_string_to_vector().
delete_vtu_and_pvd_files()
void delete_vtu_and_pvd_files (const std::string & output_path)
Delete vtu and pvd files.
Definition at line 848 of file utilities.cc.
References convert_string_to_vector().
fill_string_vectors_from_file()
void fill_string_vectors_from_file (std::map< std::string, std::vector< std::string > > & map, const std::string & file_name, const std::string & delimiter = " ")
Function that read a file that was build from a dealii table and create a map with the key being the column name and the variable the vectors of data.
Parameters
[in,out] map A map used to store the data based on column names.
[in] file_name Path to the file to read the table from.
[in] delimiter Delimiter used in the file to separate values. Default is a space (" ").
Definition at line 309 of file utilities.cc.
References convert_string_to_vector().
fill_table_from_file()
void fill_table_from_file (TableHandler & table, const std::string & file_name, const std::string & delimiter = " ")
Reads a file generated by a deal.II TableHandler and fills a TableHandler with its data.
This function reads a table from a file and populates the given TableHandler. Warning: If the table already contains data, it will be erased.
Parameters
[in,out] table The table to be filled. Existing content will be overwritten.
[in] file_name Path to the file to read the table from.
[in] delimiter Delimiter used in the file to separate values. Default is a space (" ").
Definition at line 210 of file utilities.cc.
References convert_string_to_vector().
fill_vectors_from_file()
void fill_vectors_from_file (std::map< std::string, std::vector< double > > & map, const std::string & file_name, const std::string & delimiter = " ")
function that read a file that was build from a dealii table and fill 2 vectors. The first vector contains all the columns names and the second one contained all the column data.
Parameters
[in,out] map A map used to store the data based on column names.
[in] file_name Path to the file to read the table from.
[in] delimiter Delimiter used in the file to separate values. Default is a space (" ").
Definition at line 256 of file utilities.cc.
References convert_string_to_vector().
get_dimension()
unsigned int get_dimension (const std::string & file_name)
Extract the dimension in which to run Lethe from the contents of the parameter file. This is something that we need to do before processing the parameter file since we need to know whether to use the dim=2 or dim=3 instantiation of the main classes.
Parameters
file_name[in] The file name from which dimension is read
Definition at line 632 of file utilities.cc.
References convert_string_to_vector(), and get_last_value_of_parameter().
get_last_value_of_parameter()
std::string get_last_value_of_parameter (const std::string & file_name, const std::string & parameter_name)
Retrieves the value of a specific parameter from an input file. Returns an empty string if the parameter is not found. This function is adapted from ASPECT and is mainly used to parse the dimension of the problem before creating the full parameter parser.
Parameters
[in] file_name File from which we retrieve the parameter.
[in] parameter_name Name of the parameter to retrieve.
Returns
std::string Value of the parameter, or an empty string if not found.
Definition at line 549 of file utilities.cc.
References convert_string_to_vector().
get_max_subsection_size()
int get_max_subsection_size (const std::string & file_name)
Extract the maximum value between the number of boundary conditions and the number of manifolds from the file. This value is linked to the "number" string defined in the simulation parameter file. It provides an estimate for the amount of parameters or manifolds and is used to determine the size of the vectors that will store boundary conditions and manifold data. This feature will need to be monitored extensively in the future.
Parameters
[in] file_name The file name from which the number of boundary conditions is read
Returns
The maximum number of boundary conditions or manifolds.
Definition at line 698 of file utilities.cc.
References convert_string_to_vector(), and get_max_value_of_parameter().
get_max_value_of_parameter()
int get_max_value_of_parameter (const std::string & file_name, const std::string & parameter_name)
Definition at line 588 of file utilities.cc.
References convert_string_to_vector().
make_table_scalars_tensors() [1/14]
template TableHandler make_table_scalars_tensors (const std::vector< double > & independent_values, const std::string & independent_column_name, const std::vector< std::vector< Tensor< 1, 2 > > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_scalars_tensors() [2/14]
template TableHandler make_table_scalars_tensors (const std::vector< double > & independent_values, const std::string & independent_column_name, const std::vector< std::vector< Tensor< 1, 3 > > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_scalars_tensors() [3/14]
template TableHandler make_table_scalars_tensors (const std::vector< double > & independent_values, const std::string & independent_column_name, const std::vector< Tensor< 1, 2 > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_scalars_tensors() [4/14]
template TableHandler make_table_scalars_tensors (const std::vector< double > & independent_values, const std::string & independent_column_name, const std::vector< Tensor< 1, 3 > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_scalars_tensors() [5/14]
template TableHandler make_table_scalars_tensors (const std::vector< int > & independent_values, const std::string & independent_column_name, const std::vector< std::vector< Tensor< 1, 2 > > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_scalars_tensors() [6/14]
template TableHandler make_table_scalars_tensors (const std::vector< int > & independent_values, const std::string & independent_column_name, const std::vector< std::vector< Tensor< 1, 3 > > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_scalars_tensors() [7/14]
template TableHandler make_table_scalars_tensors (const std::vector< int > & independent_values, const std::string & independent_column_name, const std::vector< Tensor< 1, 2 > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_scalars_tensors() [8/14]
template TableHandler make_table_scalars_tensors (const std::vector< int > & independent_values, const std::string & independent_column_name, const std::vector< Tensor< 1, 3 > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_scalars_tensors() [9/14]
template<int dim, typename T > TableHandler make_table_scalars_tensors (const std::vector< T > & independent_values, const std::string & independent_column_name, const std::vector< std::vector< Tensor< 1, dim > > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation = false)
Generate a table from a vector of scalar (independent variable) and a vector of vectors of Tensor<1,dim> (dependent variables).
Template Parameters
T Scalar type of independent variables.
dim Integer that denotes the number of spatial dimensions.
Parameters
[in] independent_values Vector of scalar values that serve as the independent variable (e.g., time).
[in] independent_column_name Label of the independent variable.
[in] dependent_vector Vector of vectors of Tensor<1,dim> containing dependent variables values (e.g., force).
[in] dependent_column_names Vector of strings representing the labels of dependent variables.
[in] display_precision Integer indicating the precision at which the table is written.
[in] display_scientific_notation Boolean indicating if the values should be displayed in scientific notation (true) or not (false).
Returns
Table with the independent variable values followed by the dependent variables values.
Definition at line 86 of file utilities.cc.
References convert_string_to_vector().
make_table_scalars_tensors() [10/14]
template<int dim, typename T > TableHandler make_table_scalars_tensors (const std::vector< T > & independent_values, const std::string & independent_column_name, const std::vector< Tensor< 1, dim > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation = false)
Generate a table from a vector of scalars (independent variable) and a vector of Tensor<1,dim> (dependent variables).
Template Parameters
T Scalar type of independent variables.
dim Integer that denotes the number of spatial dimensions.
Parameters
[in] independent_values Vector of scalar values that serve as the independent variable (e.g., time).
[in] independent_column_name Label of the independent variable.
[in] dependent_vector Vector of Tensor<1,dim> containing dependent variables values (e.g., force).
[in] dependent_column_names Vector of strings representing the labels of dependent variables.
[in] display_precision Integer indicating the precision at which the table is written.
[in] display_scientific_notation Boolean indicating if the values should be displayed in scientific notation (true) or not (false).
Returns
Table with the independent variable values followed by the dependent variables values.
Definition at line 50 of file utilities.cc.
References convert_string_to_vector().
make_table_scalars_tensors() [11/14]
template TableHandler make_table_scalars_tensors (const std::vector< unsigned int > & independent_values, const std::string & independent_column_name, const std::vector< std::vector< Tensor< 1, 2 > > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_scalars_tensors() [12/14]
template TableHandler make_table_scalars_tensors (const std::vector< unsigned int > & independent_values, const std::string & independent_column_name, const std::vector< std::vector< Tensor< 1, 3 > > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_scalars_tensors() [13/14]
template TableHandler make_table_scalars_tensors (const std::vector< unsigned int > & independent_values, const std::string & independent_column_name, const std::vector< Tensor< 1, 2 > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_scalars_tensors() [14/14]
template TableHandler make_table_scalars_tensors (const std::vector< unsigned int > & independent_values, const std::string & independent_column_name, const std::vector< Tensor< 1, 3 > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_scalars_vectors() [1/4]
template TableHandler make_table_scalars_vectors (const std::vector< double > & independent_values, const std::string & independent_column_name, const std::vector< std::vector< double > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_scalars_vectors() [2/4]
template TableHandler make_table_scalars_vectors (const std::vector< int > & independent_values, const std::string & independent_column_name, const std::vector< std::vector< double > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_scalars_vectors() [3/4]
template<typename T > TableHandler make_table_scalars_vectors (const std::vector< T > & independent_values, const std::string & independent_column_name, const std::vector< std::vector< double > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation = false)
Generate a table from a vector of scalars (independent variable) and a vector of vectors of scalars (dependent variables).
Template Parameters
T Scalar type of independent variables.
Parameters
[in] independent_values Vector of scalar values that serve as the independent variable (e.g., time).
[in] independent_column_name Label of the independent variable.
[in] dependent_vector Vector of vectors of scalar values containing dependant variables values.
[in] dependent_column_names Vector of strings representing the labels of dependent variables.
[in] display_precision Integer indicating the precision at which the table is written.
[in] display_scientific_notation Boolean indicating if the values should be displayed in scientific notation (true) or not (false).
Returns
Table with the independent variable values followed by the dependent variables values.
Definition at line 15 of file utilities.cc.
References convert_string_to_vector().
make_table_scalars_vectors() [4/4]
template TableHandler make_table_scalars_vectors (const std::vector< unsigned int > & independent_values, const std::string & independent_column_name, const std::vector< std::vector< double > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_tensors_scalars() [1/3]
template TableHandler make_table_tensors_scalars (const std::vector< Tensor< 1, 2 > > & independent_vector, const std::vector< std::string > & independent_column_names, const std::vector< double > & dependent_values, const std::string & dependent_column_name, const unsigned int display_precision, const bool display_scientific_notation)
make_table_tensors_scalars() [2/3]
template TableHandler make_table_tensors_scalars (const std::vector< Tensor< 1, 3 > > & independent_vector, const std::vector< std::string > & independent_column_names, const std::vector< double > & dependent_values, const std::string & dependent_column_name, const unsigned int display_precision, const bool display_scientific_notation)
make_table_tensors_scalars() [3/3]
template<int dim> TableHandler make_table_tensors_scalars (const std::vector< Tensor< 1, dim > > & independent_vector, const std::vector< std::string > & independent_column_names, const std::vector< double > & dependent_values, const std::string & dependent_column_name, const unsigned int display_precision, const bool display_scientific_notation = false)
Generate a table from a vector of Tensor<1,dim> (independent variables) and a vector of scalars (dependent variable).
Template Parameters
dim Integer that denotes the number of spatial dimensions.
Parameters
[in] independent_vector Vector of Tensor<1,dim> that serves as the independent variable (e.g., position).
[in] independent_column_names Vector of strings representing labels of the independent tensor.
[in] dependent_values Vector of doubles containing dependent variables values (e.g., force).
[in] dependent_column_name Label of the dependent variable.
[in] display_precision Integer indicating the precision at which the table is written.
[in] display_scientific_notation Boolean indicating if the values should be displayed in scientific notation (true) or not (false).
Returns
Table with the independent variables values followed by the dependent variable values.
Definition at line 174 of file utilities.cc.
References convert_string_to_vector().
make_table_tensors_tensors() [1/3]
template TableHandler make_table_tensors_tensors (const std::vector< Tensor< 1, 2 > > & independent_values, const std::vector< std::string > & independent_column_names, const std::vector< Tensor< 1, 2 > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_tensors_tensors() [2/3]
template TableHandler make_table_tensors_tensors (const std::vector< Tensor< 1, 3 > > & independent_values, const std::vector< std::string > & independent_column_names, const std::vector< Tensor< 1, 3 > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation)
make_table_tensors_tensors() [3/3]
template<int dim> TableHandler make_table_tensors_tensors (const std::vector< Tensor< 1, dim > > & independent_vector, const std::vector< std::string > & independent_column_names, const std::vector< Tensor< 1, dim > > & dependent_vector, const std::vector< std::string > & dependent_column_names, const unsigned int display_precision, const bool display_scientific_notation = false)
Generate a table from a vector of Tensor<1,dim> (independent variables) and a vector of Tensor<1,dim> (dependent variables).
Template Parameters
dim Integer that denotes the number of spatial dimensions.
Parameters
[in] independent_vector Vector of Tensor<1,dim> that serves as the independent variable (e.g., position).
[in] independent_column_names Vector of strings representing labels of the independent tensor.
[in] dependent_vector Vector of vectors of Tensor<1,dim> containing dependent variables values (e.g., force).
[in] dependent_column_names Vector of strings representing the labels of dependent variables.
[in] display_precision Integer indicating the precision at which the table is written.
[in] display_scientific_notation Boolean indicating if the values should be displayed in scientific notation (true) or not (false).
Returns
Table with the independent variables values followed by the dependent variables values.
Definition at line 132 of file utilities.cc.
References convert_string_to_vector().
parse_args()
std::tuple< std::map< std::string, bool >, std::vector< std::string > > parse_args (int argc, char ** argv)
Parse the arguments given to the application.
Parameters
[in] argc Number of arguments
[in] argv Array of strings representing the arguments
Returns
Tuple containing a map with the command line flags and a boolean set to 1 for the specific flag; and a vector of strings with the rest of the arguments that are not flags; in Lethe, this corresponds to the parameter file given to the application.
Definition at line 768 of file utilities.cc.
References convert_string_to_vector().
print_parameters_to_output_file()
void print_parameters_to_output_file (const ConditionalOStream & pcout, const ParameterHandler & prm, const std::string & file_name)
Print the parameters given by the parameter file of the application.
Parameters
[in] pcout Parallel output stream
[in] prm Object containing the parameters parsed from the parameter file
Definition at line 814 of file utilities.cc.
References convert_string_to_vector(), and get_last_value_of_parameter().
print_version_info()
void print_version_info (const ConditionalOStream & pcout)
Print the information of the deal.II and Lethe branches used to run an application in the "git describe" format.
Parameters
[in] pcout Parallel output stream
Definition at line 737 of file utilities.cc.
References convert_string_to_vector().